# Generated by Django 2.2.12 on 2020-04-11 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200411_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimburse',
            name='zip_code',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
