# Generated by Django 2.2.12 on 2020-04-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20200409_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='insurance_exists',
            field=models.CharField(choices=[('INSURED', 'Insured'), ('UNINSURED', 'Uninsured')], default='INSURED', max_length=9),
        ),
    ]
