# Generated by Django 2.2.12 on 2020-04-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20200409_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='insurance_exists',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
